### ISSUE TITLE
Make ess_rhat return NaN instead of erroring

### ISSUE THREAD

**Issue by sethaxen** [TuringLang/MCMCDiagnosticTools.jl#117]
Currently MCMCChains automatically displays our diagnostics for `Chains`. But for chains with less than 10 draws, each diagnostic that calls `ess_rhat` will error at the following line due to splitting: https://github.com/TuringLang/MCMCDiagnosticTools.jl/blob/7d78e5d633c4e359be35b39ae2985c52aab16429/src/ess_rhat.jl#L465

This erroring is a nuisance to handle in either PosteriorStats or MCMCChains. I suggest we instead return `NaN`s in such cases and raise an informative warning about why `ess_rhat` failed. This would probably resolve https://github.com/TuringLang/MCMCChains.jl/issues/447 and https://github.com/TuringLang/MCMCChains.jl/issues/410

**Comment by devmotion** [comment]
We changed it to an error in https://github.com/TuringLang/MCMCDiagnosticTools.jl/pull/64 but I agree that probably `NaN` (+ `@warn`?) would be easier to handle for downstream packages.
